booktitle: Материалы 9-й всероссийской научной конференции по проблемам информатики
series: СПИСОК '22
year: 2022
issn: 2310-4724, 2310-4732
location: Санкт-Петербург, Россия
publisher: ВВМ
address: Санкт-Петербург, Россия