name: sections-generator

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: run script
      run: |
        python script.py .
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: sections-generated
