name: sections-generator

on:
  push:
    branches:
      -main

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: run script
      run: python3 sections/sections-generator.py
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: commit changes
      with:
        commit_message: sections-generated
